[package]
name = "Hexray-VC"
version = "0.1.0"
edition = "2024"
build = "build/main.rs"

[[bin]]
name = "VC"
path = "src/main.rs"
test = false
bench = false

[dependencies]
panic-halt = "0.2"

[build-dependencies]
cc = "1.0"       # To compile the C code
bindgen = "0.72" # To generate Rust FFI bindings from C headers

# Recommended optimization settings for embedded projects
[profile.release]
codegen-units = 1 # Better optimizations
lto = true        # Link-time optimization (reduces binary size)
opt-level = "z"   # Optimize for size
debug = true      # Keep debug symbols for flashing/debugging
