[package]
name = "Consolidated-Firmware"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["gte7", "shared", "tests"]

[profile.release]
lto = true # Link-time optimization (reduces binary size)

[profile.release.package.gte7]
codegen-units = 1 # Better optimizations
opt-level = "z"   # Optimize for size
debug = true      # Keep debug symbols for flashing/debugging
